# Generated by Django 3.2.9 on 2023-05-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='收藏视频时间'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建收藏夹时间'),
        ),
    ]
