# Generated by Django 3.2.9 on 2023-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='video',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='评论者ID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.IntegerField(null=True, verbose_name='被评论的视频ID'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='点赞者ID'),
        ),
        migrations.AddField(
            model_name='like',
            name='video_id',
            field=models.IntegerField(null=True, verbose_name='被点赞的视频ID'),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment_id',
            field=models.IntegerField(null=True, verbose_name='所属评论ID'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='回复者ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='所属用户'),
        ),
    ]
