# Generated by Django 3.2.5 on 2023-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20230515_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_amount',
            field=models.IntegerField(default=0, verbose_name='总点赞数'),
        ),
        migrations.AddField(
            model_name='video',
            name='comment_amount',
            field=models.IntegerField(default=0, verbose_name='总评论数'),
        ),
    ]
