# Generated by Django 3.2.9 on 2023-05-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='like',
            new_name='likes',
        ),
    ]
