# Generated by Django 3.2.5 on 2023-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Collect',
        ),
        migrations.AddField(
            model_name='video',
            name='hotness',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
    ]
