# Generated by Django 3.2.5 on 2023-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20230516_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='video_id',
            field=models.IntegerField(default=1, null=True, verbose_name='被回复的视频ID'),
        ),
    ]
