# Generated by Django 3.2.9 on 2023-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20230520_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='JobId',
            field=models.CharField(max_length=255, null=True, verbose_name='腾讯云自动审核ID'),
        ),
    ]
