# Generated by Django 3.2.9 on 2023-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='cover_url',
            field=models.CharField(default='https://aamofe-1315620690.cos.ap-beijing.myqcloud.com/favorite_cover/0.png', max_length=128, verbose_name='封面路径'),
        ),
    ]
