# Generated by Django 3.2.9 on 2023-06-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_comment_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='播放记录所有者')),
                ('video_id', models.IntegerField(default=1, null=True, verbose_name='观看的视频ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='观看的时间')),
            ],
        ),
    ]
