# Generated by Django 4.1.7 on 2023-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(verbose_name='粉丝ID')),
                ('following_id', models.IntegerField(verbose_name='被关注者ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('avatar_url', models.CharField(max_length=255, verbose_name='头像地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Vcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcode', models.CharField(max_length=6, verbose_name='验证码')),
                ('to_email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('code_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
        ),
    ]
