# Generated by Django 3.2.9 on 2023-05-15 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='个性签名'),
            preserve_default=False,
        ),
    ]
