# Generated by Django 3.2.9 on 2023-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcode', models.CharField(max_length=6, verbose_name='验证码')),
                ('to_email', models.CharField(max_length=20, verbose_name='邮箱')),
            ],
        ),
    ]
