# Generated by Django 4.1.7 on 2023-05-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_id',
            field=models.CharField(max_length=10, verbose_name='粉丝ID'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following_id',
            field=models.CharField(max_length=10, verbose_name='被关注者ID'),
        ),
    ]
