# Generated by Django 3.2.9 on 2023-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='通知对象ID')),
                ('content', models.CharField(max_length=255, verbose_name='通知内容')),
                ('link', models.CharField(max_length=255, verbose_name='跳转链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通知创建时间')),
            ],
        ),
    ]
