# Generated by Django 4.1.7 on 2023-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.IntegerField(verbose_name='通知对象ID')),
                ('send_from', models.CharField(max_length=20, verbose_name='通知者')),
                ('content', models.CharField(max_length=255, verbose_name='通知内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通知创建时间')),
            ],
        ),
    ]
