# Generated by Django 4.1.7 on 2023-05-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='notification',
        #     name='link',
        # ),
        # migrations.RemoveField(
        #     model_name='notification',
        #     name='user_id',
        # ),
        migrations.AddField(
            model_name='notification',
            name='send_from',
            field=models.CharField(default='', max_length=10, verbose_name='通知者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to',
            field=models.CharField(default='', max_length=10, verbose_name='通知对象ID'),
            preserve_default=False,
        ),
    ]
